name: test2

on:
  push:
    branches:
      - imooc888
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #git pull,第三方的cations
      - name: Use Node.js
        uses: actions/setup-node@v1 #安装nodejs,第三方的cations
        with:
          node-version: 14
      - name: lint and test
        run:  
              npm i
              npm run lint
              npm run test: remote